// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _0524FirstMVC.Data;

namespace _0524FirstMVC.Migrations
{
    [DbContext(typeof(MemberContext))]
    [Migration("20220524100620_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_0524FirstMVC.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brief = "中華大學 觀光與會展活動學系 最愛南柱赫!!!!!",
                            Name = "李家萱",
                            Photo = "https://raw.githubusercontent.com/JiaXuan1083/FileStorage/main/IMG_7403.JPG"
                        },
                        new
                        {
                            Id = 2,
                            Brief = "中華大學 生物資訊學系 打羽球",
                            Name = "廖培余",
                            Photo = "https://raw.githubusercontent.com/yu1129/hard/main/%E4%BD%99.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Brief = "中華大學 生物資訊學系 聽音樂",
                            Name = "吳霈玟",
                            Photo = "https://raw.githubusercontent.com/wen-0510/FileStorages/main/1.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Brief = "中華大學 生物資訊學系 愛貓",
                            Name = "朱彥蓉",
                            Photo = "https://raw.githubusercontent.com/t333685/t333685.github.io/590201655655be034c9866169ddbab949d138e33/S__7020548.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Brief = "中華大學 生物資訊學系 瑜珈",
                            Name = "盧致文",
                            Photo = "https://raw.githubusercontent.com/chihwen1215/FileStorage/main/S__35127335.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Brief = "中華大學 工業管理學系 打羽球",
                            Name = "楊子慧",
                            Photo = "https://raw.githubusercontent.com/LittleY11/FileStorage/main/photo.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Brief = "中華大學 資訊工程學系 看比賽",
                            Name = "戴閣廷",
                            Photo = "https://raw.githubusercontent.com/hi8787h/hi8787h.github.io/main/photo/Myphoto.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
