// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _0524FirstMVC.Data;

namespace _0524FirstMVC.Migrations
{
    [DbContext(typeof(MemberContext))]
    [Migration("20220524103716_InitialDB2")]
    partial class InitialDB2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_0524FirstMVC.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brief = "平時喜好打APEX、LOL最近每天去打撞球",
                            Name = "王泓凱",
                            Photo = "https://raw.githubusercontent.com/PurerKai/MVCAPI/main/myself.png"
                        },
                        new
                        {
                            Id = 2,
                            Brief = "甜點愛好者",
                            Name = "王俐璇",
                            Photo = "https://raw.githubusercontent.com/Lemon-2001/FileStoreage/main/MVC/Hsuan.jpeg"
                        },
                        new
                        {
                            Id = 3,
                            Brief = "抽菸,飆車,",
                            Name = "楊明翰",
                            Photo = "https://raw.githubusercontent.com/ert3455668/ert3455668.github.io/main/JavaScript/77F5723D-D640-4DA9-A57C-2C1542D58145.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Brief = "看女團",
                            Name = "昱寬",
                            Photo = "https://raw.githubusercontent.com/Kuan1215/FileStorage/main/D6480B08-E095-456D-BB43-C0372D0FB0AC.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Brief = "聽音樂、看看書、過生活",
                            Name = "吳奕君",
                            Photo = "https://raw.githubusercontent.com/Chun-2000/Chun-2000.github.io/main/MyPhoto.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Brief = "充滿文學氣質的文藝青年",
                            Name = "羅世晏",
                            Photo = "https://raw.githubusercontent.com/LoShinYen/FileStorages/main/S__5750791.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Brief = "可愛又迷人的反派角色",
                            Name = "張添宇",
                            Photo = "https://raw.githubusercontent.com/RainRoc1222/RainRoc1222.github.io/main/178099682_6502551609770280_5658538484540389917_n.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Brief = "可以坐著就不要站著，可以躺著就不要坐著",
                            Name = "郭柏言",
                            Photo = "https://raw.githubusercontent.com/lazyorangecat/lazyorangecat.github.io/main/XiJiangHua%20ASP.NET%20Core%20MVC/0524FirstMVC/12.jpeg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
