// <auto-generated />
using BackendWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendWebApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220501142107_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackendWebApi.Models.Champion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Armor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Attackrange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Chinese")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Hp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Movespeed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Spellblock")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Champions");
                });
#pragma warning restore 612, 618
        }
    }
}
